vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone = "ap-southeast-1b"
env = "dev"
my_ip = "MY_IP_ADDRESS_HERE"
instance_type = "t2.micro"
public_key_location = "/Users/jeshocarmel/.ssh/id_rsa.pub"